import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  leoSidebar: [
    {
      type: 'category',
      label: 'Leo Rover',
      link: { type: 'doc', id: 'leo-rover' },
      items: [{ type: 'autogenerated', dirName: 'leo-rover' }],
      collapsible: false,
    },
  ],
  raphaSidebar: [{ type: 'autogenerated', dirName: 'rapha-rover' }],
  guidelines: [{ type: 'autogenerated', dirName: 'guidelines' }],
};

export default sidebars;
