import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  integrationSidebar: [
    {
      type: 'category',
      label: 'Leo Rover Integrations',
      link: {
        type: 'generated-index',
        title: 'Leo Rover Integrations',
        description:
          'Integrations connect third-party hardware and software to your Leo Rover. Browse various sensors, actuators, and software tools below, each with step-by-step setup guides.',
        slug: '/',
      },
      items: [{ type: 'autogenerated', dirName: '.' }],
      collapsible: false,
    },
  ],
};

export default sidebars;
