import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  integrationSidebar: [
        {
      type: 'category',
      label: 'Integrations',
      link: { type: 'generated-index', title: 'Integrations', slug: '/' },
      items: [{ type: 'autogenerated', dirName: '.' }],
      collapsible: false,
    },
  ],
};

export default sidebars;
