import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  raphSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Integrations',
      href: '/raph-integrations',
      className: 'sidebar-integrations-link',
    },
  ],
};

export default sidebars;
